name: Trigger files.py Script

on:
  schedule:
    # Run at 6:00 PM UTC on Monday to Friday (cron format)
    - cron: '45 17 * * 1-5'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify the Python version you want to use

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r google_automate/requirements.txt  # Install dependencies if applicable
    - name: check cwd
      run: pwd 

    - name: Run files.py scriptç
      env:
        URL_LOG: ${{ secrets.URL_LOG }}
        EMAIL: ${{ secrets.EMAIL }}
        RECIPIENT: ${{ secrets.RECIPIENT }}
        PASSWORD_AUTO: ${{ secrets.PASSWORD_AUTO }}
      run: |
        python gmail_automate/send_reminder.py
      
